
import { ReduxProvider } from "@/redux/provider";
import "./globals.css";



export const metadata = {
  title: "Create gnaoui App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
    <html >
      <body
      
      >
        {children}
      </body>
    </html>
    </ReduxProvider>
  );
}
